name: Update Subscription

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📦 Install subconverter
        run: |
          git clone https://github.com/tindy2013/subconverter.git
          cd subconverter
          chmod +x subconverter

      - name: ⚙️ Generate Subscription
        run: |
          cd subconverter

          URLS=$(paste -sd '|' ../sources.txt)

          echo "url=$URLS" > pref.ini
          echo "target=clash" >> pref.ini
          echo "emoji=true" >> pref.ini
          echo "list=true" >> pref.ini
          echo "sort=true" >> pref.ini
          echo "udp=true" >> pref.ini
          echo "scv=true" >> pref.ini
          echo "fdn=true" >> pref.ini
          echo "config=../config.yaml" >> pref.ini
          echo "output=../output.yaml" >> pref.ini

          ./subconverter

      - name: 📤 Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output.yaml
          git commit -m "update subscription" || echo "no changes"
          git push
